# Generated by Django 3.0.5 on 2020-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('itemName', models.CharField(max_length=100)),
                ('itemPrice', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=20)),
                ('img_1', models.FileField(upload_to='items/')),
                ('img_2', models.FileField(upload_to='items/')),
                ('dateUploaded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passcode', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('img', models.FileField(upload_to='users/')),
            ],
        ),
    ]
