# Generated by Django 3.0.5 on 2020-04-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=3000)),
                ('img', models.FileField(null=True, upload_to='chat_images/')),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('dateSent', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('lastMessage', models.CharField(max_length=3)),
            ],
        ),
    ]
