# Generated by Django 3.0.5 on 2020-04-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chattable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemsTable',
        ),
    ]
