# Generated by Django 3.0.5 on 2020-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_itemstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('emailId', models.IntegerField()),
                ('itemName', models.CharField(max_length=100)),
                ('itemPrice', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=20)),
                ('img_1', models.FileField(upload_to='items/')),
                ('img_2', models.FileField(upload_to='items/')),
                ('dateUploaded', models.DateTimeField()),
            ],
        ),
    ]
