# Generated by Django 3.0.5 on 2020-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_communicatingpartyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattable',
            name='receiver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chattable',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
