# Generated by Django 3.0.5 on 2020-04-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200428_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattable',
            name='receiver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chattable',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
