# Generated by Django 3.0.5 on 2020-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200428_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattable',
            name='receiver',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='chattable',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
