# Generated by Django 3.0.5 on 2020-04-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginForm',
            new_name='adminTable',
        ),
    ]
